name: Deploy Bicep Template to Azure

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Script
              run: echo "Starting Bicep Deployment to Microsoft Azure"

            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS}}

            - name: Create Resource Group if not exists
              run: |
                  az group create --name rg-github-bicep-lab --location eastus
              
            - name: Deploy the Bicep template
              uses: azure/arm-deploy@v1
              with:
                resourceGroupName: "rg-github-bicep-lab"
                template: main.bicep
                parameters: |
                    namePrefix=pzeaghlab1



